# Generated by Django 5.2.7 on 2025-10-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default=1, max_length=100, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
